import { Navbar } from '@/components/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

const qara = localFont({
    src: [
        {
            path: '../public/fonts/qara.ttf',
            weight: '400',
        },
    ],
    variable: '--font-qara',
});

const sfPro = localFont({
    src: [
        {
            path: '../public/fonts/sf-Pro-Display-Light.ttf',
        },
    ],

    variable: '--font-sfpro',
});
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`  ${sfPro.variable} ${qara.variable} font-sfpro`}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
