import { Navbar } from '@/components/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
const inter = Inter({ subsets: ['latin'] });

const lavish = localFont({
    src: [
        {
            path: '../public/fonts/Lavish.ttf',
            weight: '400',
        },
    ],
    variable: '--font-lavish',
});

const qara = localFont({
    src: [
        {
            path: '../public/fonts/qara.ttf',
            weight: '400',
        },
    ],
    variable: '--font-qara',
});

const alore = localFont({
    src: [
        {
            path: '../public/fonts/Alore_Medium.ttf',
            weight: '400',
        },
    ],
    variable: '--font-alore',
});
const sfPro = localFont({
    src: [
        {
            path: '../public/fonts/sf-pro-text-regular.ttf',
        },
        {
            path: '../public/fonts/sf-pro-text-medium.ttf',
        },
        {
            path: '../public/fonts/sf-pro-text-light.ttf',
        },
        {
            path: '../public/fonts/sf-Pro-Display-Thin.ttf',
        },
        {
            path: '../public/fonts/sf-Pro-Display-Light.ttf',
        },
    ],

    variable: '--font-sfpro',
});
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
// ${inter.className} // ${lavish.variable}
export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body
                className={` ${lavish.variable}  ${sfPro.variable} ${alore.variable} ${qara.variable} font-sfpro`}
            >
                <Navbar />
                {children}
            </body>
        </html>
    );
}
